[package]
name = "create-bitcoin-address"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "=0.8.5"
secp256k1 = "=0.24.0"
bitcoin = "=0.29.1"
sha256 = "=1.0.3"
